container:
  image: termux/package-builder:latest
  cpu: 8
  memory: 16

##
## * Only test build. No uploads here.
## * Timeout is 120 minutes.
##

task:
  name: Test build

  timeout_in: 120m

  environment:
    matrix:
      TERMUX_ARCH: aarch64
      TERMUX_ARCH: arm
      TERMUX_ARCH: i686
      TERMUX_ARCH: x86_64

  build_script: |
    bash ./scripts/build/ci/cirrus-ci_dispatcher.sh

  output_artifacts:
    path: "./debs/*.deb"
