name: Package updates

on:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Process package updates
      env:
        GITHUB_API_TOKEN: ${{ secrets.GH_API_KEY }}
        BUILD_PACKAGES: "true"
        GIT_COMMIT_PACKAGES: "true"
        GIT_PUSH_PACKAGES: "true"
      run: |
        git config --global user.name "Termux Github Actions"
        git config --global user.email "leonid.pliushch@gmail.com"
        bash ./scripts/updates/check-updates.sh
